### ISSUE TITLE
Pry::MethodInfo.info_for fails for methods defined in Ruby

### ISSUE THREAD

**Issue by dgutov** [pry/pry-doc#14]
In 0.4.6.

It works in 0.4.4, and I'm kind of depending on it in dgutov/robe. Is that an unreasonable assumption?

I figured since doc retrieval is proxied to YARD anyway, it should be able to handle both kinds of methods. Here's an example stack trace:

```
irb(main):004:0> Pry::MethodInfo.info_for(Yajl::Parser.method(:parse))
NameError: undefined method `parse' for class `Class'
    from /home/gutov/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/pry-doc-0.4.6/lib/pry-doc.rb:49:in `method'
    from /home/gutov/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/pry-doc-0.4.6/lib/pry-doc.rb:49:in `block in aliases'
    from /home/gutov/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/pry-doc-0.4.6/lib/pry-doc.rb:49:in `select'
    from /home/gutov/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/pry-doc-0.4.6/lib/pry-doc.rb:49:in `aliases'
    from /home/gutov/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/pry-doc-0.4.6/lib/pry-doc.rb:72:in `registry_lookup'
    from /home/gutov/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/pry-doc-0.4.6/lib/pry-doc.rb:65:in `cached?'
    from /home/gutov/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/pry-doc-0.4.6/lib/pry-doc.rb:207:in `cache'
    from /home/gutov/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/pry-doc-0.4.6/lib/pry-doc.rb:87:in `info_for'
    from (irb):4
    from /home/gutov/.rbenv/versions/1.9.3-p429/bin/irb:12:in `<main>'
```
